AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - ".git/**/*"
    - "db/**/*"
Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "bin/bundle"

Metrics/CyclomaticComplexity:
  Exclude:
    - "bin/bundle"

Metrics/MethodLength:
  Exclude:
    - "bin/bundle"
